### PR TITLE
Added inputType config value and ability to retain original input type property

### LINKED ISSUE #31: Using a number keyboard on mobile devices / setting the input pattern.
As currently written, the plugin has the "type" property of the resulting input hard-coded as "text". This creates a type="text" input regardless of the original input type (for example, "number"). This hurts the "mobile-friendliness" claim of the addon because if a user tries to interact with an input that is supposed to be of a particular type, the mobile browser will instead revert to full-text input.

### PR DESCRIPTION
**Pull request by jboyer87**
Fixes #31. Adds a new inputType config value, which defaults to text, and the ability to retain the original input type property.

### CODE REVIEW

**Comment by shaack** [comment]
Good recommendation. Thanks, looks good your patch. I will merge it, when I have some time this weekend.

**Comment by shaack** [comment]
Hi, I merged ist, tested it,... and reverted it. Because another type than text makes no sense. If you set it to number, the floating point examples in german localization will not work and you have those small arrows in the input in Chrom:
Input type Number

**Comment by jboyer87** [comment]
That's interesting. Do you have another solution in mind for mobile keyboards defaulting to text input for numbers/floating points/etc? May have to come up with another approach.

**Comment by shaack** [comment]
Maybe, it could work with the "pattern" parameter.
https://stackoverflow.com/a/32972402 
When I have time I will make some tests with german number input.

**Comment by V-ed** [comment]
As I mentionned in an issue of my own fork of this project, this library could hide the "twisties" as I call them via some custom css styling (that would be added in a `style` attribute if the type is number) : https://css-tricks.com/snippets/css/turn-off-number-input-spinners/

I plan to write the code for that and test it during the next few days, I'll update in my issue and in here to give you some progress.

**Comment by V-ed** [comment]
Testing some more and there seems to be a `inputmode="numeric"` property that we can add to an input of type `text`, which, on mobile (at least, on my Android phone on Chrome), pops up the number pad while keeping the properties of the text input.

That `inputmode` attribute seems to have a relatively bad compatibility score tho ([can I use reference](https://caniuse.com/#feat=input-inputmode)), but would be already better than nothing. If Chrome on Android and Safari on iOS supports it (which they do if when looking at that can I use table), it should be enough to be added as a default.

**Comment by shaack** [comment]
Good idea, thanks. I will try it.

**Comment by jboyer87** [comment]
> Testing some more and there seems to be a `inputmode="numeric"` property that we can add to an input of type `text`, which, on mobile (at least, on my Android phone on Chrome), pops up the number pad while keeping the properties of the text input.
> 
> That `inputmode` attribute seems to have a relatively bad compatibility score tho ([can I use reference](https://caniuse.com/#feat=input-inputmode)), but would be already better than nothing. If Chrome on Android and Safari on iOS supports it (which they do when looking at that can I use table), it should be enough to be added as a default.

Yes, that's actually what I was doing in the original pull request. I gave an option to customize the input type and then was using numeric. Works perfectly. I am still using my fork with that fix.

**Comment by V-ed** [comment]
@jboyer87 If by "in the original pull request" you meant this one, then no, what I described is not what you done :

You added an option to change the _type_ of the input.

What I described is another attribute completely, keeping the `<input type="text">`, so therefore keeping the locale formatting for German (for example), but add a new attribute `inputmode="numeric"`. This makes mobile browser know that despite being a type="text", the intended input is numeric, so the number keyboard is shown.

---

I'm not against what you did, I had in mind to do _exactly_ what you did here, but diverted once I saw the problem with locale formatting. The little buttons in the input of type number can be hidden, so that wasn't a real problem.

Hope it's a bit clearer now! :)

**Comment by jboyer87** [comment]
> @jboyer87 If by "in the original pull request" you meant this one, then no, what I described is not what you done :
> 
> You added an option to change the _type_ of the input.
> 
> What I described is another attribute completely, keeping the `<input type="text">`, so therefore keeping the locale formatting for German (for example), but add a new attribute `inputmode="numeric"`. This makes mobile browser know that despite being a type="text", the intended input is numeric, so the number keyboard is shown.
> 
> I'm not against what you did, I had in mind to do _exactly_ what you did here, but diverted once I saw the problem with locale formatting. The little buttons in the input of type number can be hidden, so that wasn't a real problem.
> 
> Hope it's a bit clearer now! :)

Sorry, I misunderstood (or read too quickly) your initial reply. Your solution is definitely an improvement - that makes sense. I think that your suggestion is more compatible than mine. Great idea! 🎊

**Pull request merged**
