### PR TITLE
Prevent resetting empty value to zero on mutation event

### PR DESCRIPTION
**Pull request by maurojs10**
Resolves issue #51

### CODE REVIEW

**Comment by shaack** [comment]
Sorry, this fix does not really work. You can test it in index.html. Unter section "Dynamically handling of the class attribute" if you delete the "50" in the input (input is empty), than change "CSS Class" to "is-invalid" (or something else). Expected is: the input should stay empty. The behaviour is: The 50 is coming back.

**Comment by maurojs10** [comment]
Sorry about that.

I've made some changes to this fix.

How about now?

**Comment by shaack** [comment]
Seems to work. Well done, and thank you!

**Comment by maurojs10** [comment]
Thank you so much for this excellent plugin and for taking the time to review my fix.

**Pull request merged**
